### ISSUE TITLE
Bullarna smakar för salt

### ISSUE THREAD

**Issue by Poiku** [oflisback/recept#1]
Jag upplever ett problem med saltnivån, är ungefär 0,3% för hög vid varje instans av matlagning.exe.

**Comment by oflisback** [comment]
Tack snälla för att du tog dig tid att rapportera den här buggen det glädjer oss maintainers att även windows avnjutare som du kan logga in på github och det här projektet. Jag har inte själv provat att använda receptet med matlagning.exe, kan man köra det genom Wine? Så klart kan du också kvantifiera den upplevda sältan ner till tiondels procent. Nyfiket!
